import { Router } from "express";
import { registerAuthRoutes } from "./auth";
import { registerUserRoutes } from "./users";
import { registerShipmentRoutes } from "./shipments";
import { registerTicketRoutes } from "./tickets";
import { registerProjectRoutes } from "./projects";
import { registerOkrRoutes } from "./okrs";
import { registerTaskRoutes } from "./tasks";
import { registerKnowledgeBaseRoutes } from "./knowledge";
import { registerAIRoutes } from "./ai";
import { registerNotificationRoutes } from "./notifications";
import { registerSettingsRoutes } from "./settings";
import { registerSlaRoutes } from "./slas";
import { registerCepRoutes } from "./cep";
import { registerIntegrationRoutes } from "./integrations";
import { registerLabelRoutes } from "./labels";
import { registerPricingRoutes } from "./pricing";
import { registerUpdateRoutes } from "./updates";
import { registerGitAnalyticsRoutes } from "./git-analytics";
import { registerMetaRoutes } from "./metas";
import { registerFlowchartRoutes } from "./flowcharts";
import { registerOmieRoutes } from "./omie";
import { registerEstoqueRoutes } from "./estoques";
import { registerDevToolsRoutes } from "./dev-tools";
import { registerWorkspaceRoutes } from "./workspace";
import { registerTriagemRoutes } from "./triagem";
import { registerAvaliacoesRoutes } from "./avaliacoes";
import { registerComercialKpisRoutes } from "./comercial-kpis";
import { registerExternalRoutes } from "./external.js";

export function registerModularRoutes(app: Router) {
  const router = Router();

  registerAuthRoutes(router);
  registerUserRoutes(router);
  registerShipmentRoutes(router);
  registerTicketRoutes(router);
  registerProjectRoutes(router);
  registerOkrRoutes(router);
  registerTaskRoutes(router);
  registerKnowledgeBaseRoutes(router);
  registerAIRoutes(router);
  registerNotificationRoutes(router);
  registerSettingsRoutes(router);
  registerSlaRoutes(router);
  registerCepRoutes(router);
  registerIntegrationRoutes(router);
  registerLabelRoutes(router);
  registerPricingRoutes(router);
  registerUpdateRoutes(router);
  registerGitAnalyticsRoutes(router);
  registerMetaRoutes(router);
  registerFlowchartRoutes(router);
  registerOmieRoutes(router);
  registerEstoqueRoutes(router);
  registerDevToolsRoutes(router);
  registerWorkspaceRoutes(router);
  registerTriagemRoutes(router);
  registerAvaliacoesRoutes(router);
  registerComercialKpisRoutes(router);
  registerExternalRoutes(router);

  app.use(router);
}
